### ISSUE TITLE
建立好环境后，无法访问，错误信息如下

### ISSUE THREAD

**Issue by qinyadong** [fex-team/fis3-smarty#28]
Fatal error: Uncaught SmartyException: Unable to load template file 'C:\Users\qyd\AppData\Local.fis3-tmp\www\template/A/index.tpl' in C:\Users\qyd\AppData\Local.fis3-tmp\www\smarty\sysplugins\smarty_internal_templatebase.php:127 Stack trace: #0 C:\Users\qyd\AppData\Local.fis3-tmp\www\smarty\sysplugins\smarty_internal_templatebase.php(374): Smarty_Internal_TemplateBase->fetch('C:\Users\qyd\Ap...', NULL, NULL, Object(Smarty), true) #1 C:\Users\qyd\AppData\Local.fis3-tmp\www\fisdata\TestData.class.php(100): Smarty_Internal_TemplateBase->display('C:\Users\qyd\Ap...') #2 C:\Users\qyd\AppData\Local.fis3-tmp\www\index.php(53): TestData::renderHelper(Object(Smarty), 'C:\Users\qyd\Ap...') #3 C:\Users\qyd\AppData\Local.fis3-tmp\www\index.php(146): fis_debug_render_smarty() #4 {main} thrown in C:\Users\qyd\AppData\Local.fis3-tmp\www\smarty\sysplugins\smarty_internal_templatebase.php on line 127

**Comment by qinyadong** [comment]
是系统路径分割符的问题吗？系统是windows10

**Comment by qinyadong** [comment]
为什么会出现这个问题，是fis3-smarty本省的bug?

**Comment by oxUnd** [comment]
两个模块都 release 了么？

**Comment by eugeneCN** [comment]
你好，这个问题解决了吗，同求！

**Comment by oxUnd** [comment]
URL 错了吧，看到没，没有 page 那一层，咋访问到 page 下的 tpl ?
