### ISSUE TITLE
fis3-smarty 脚手架问题

### ISSUE THREAD

**Issue by whatwg6** [fex-team/fis3-smarty#31]
;  快速启动一个项目
mkdir demo
cd demo
fis3 init php-smarty

然后 fis3 server start
fis3 release -wL

之后为什么看不到it works？？？？

需要配置server.conf吗？

**Comment by oxUnd** [comment]
这个问题最后怎么样了？

**Comment by whatwg6** [comment]
需要插件和 配置Server.conf就可以看到了…

**Comment by whatwg6** [comment]
当时用这个写的毕设仓库在这https://github.com/forzeny/graduation 后端是php-ci 也有相应的仓库，希望会帮助到大家，当时搭环境真是搭建蒙圈了。。。。
