### ISSUE TITLE
大神关于fis3解析PHP文件

### ISSUE THREAD

**Issue by watersea** [fex-team/fis3-smarty#38]
我们的项目用smarty来做的，我想问一下fis3 中如何去解析相应的PHP文件，然后映射到写好tpl文件中，有没有可以参考的文章之类的

**Comment by oxUnd** [comment]
这个可以看看 smarty 官网指导。

大概这样一个过程

```php
<?php

class IndexController {
  public function indexAction() {
    $objects = array('title' => 'This is a test');
    return $this->view('foo/index/index.tpl', $objects);
  }

  protected function view($tpl, $objects) {
    $smarty = new Smarty();
    $smarty->assign($objects);
    $smarty->display($tpl);
  }
}
```

- https://github.com/fis-dev/fis-plus-server-framework/blob/master/index.php#L142-L149

**Comment by watersea** [comment]
是这样的大神，我现在在本地测试环境下运行项目，咱们这个fis3 不去设置输出目录，只是输出到默认的www目录下面，在这种情况下，启动web server ，在这种情况下，一般都是直接解析html文件然后打开浏览器，但是我们这边 的项目是没有html，现在想让他走PHP路径去解析对应的tpl文件，然后打开浏览器，不知道您能理解我说的这些吗？您这边有什么好的建议吗？
