### ISSUE TITLE
在.tpl模板文件中使用php文件里的变量问题

### ISSUE THREAD

**Issue by ClausClaus** [fex-team/fis3-smarty#39]
最近公司在用fis3的smarty解决方案重公司的一个电商项目，目前遇到的问题是在像顶部导航，用户信息侧边栏，底部导航这些组件中的某些变量是通用的变量。现在fis3Smarty解决方案中有关于在前端使用php全局变量的方法吗，简单的说就是一个变量可以用在其他所有的页面，而不是每个页面都需要重新引入一次这个变量。还望高人指教。。。多谢了

**Comment by SeanKChan** [comment]
同求，如何把变量存储在工程的内存中

**Comment by ClausClaus** [comment]
好多天了，项目已到后期。我这里是让后端php做l了注入服务解决这个问题，fis3开发总能遇到这样那样的问题。。。。swf文件都加载不出来。。。只能扔到后端那边加载。。

**Comment by oxUnd** [comment]
有点开发的常识行不行？

你 PHP 本身每次请求都是会初始化一个新的环境（上下文），那么对于你多个 TPL 的渲染，每个页面用到的数据不得每次请求都由 PHP 重新获取并在渲染模板的时候传给模板？

另外 swf 加载不了是个什么意思，你不都是服务器加载资源么，服务器加载不了资源无非就是 url 不对。
