### ISSUE TITLE
fis 安装，提示Java不支持

### ISSUE THREAD

**Issue by liguanrui** [fex-team/fis3-smarty#4]
运行&安装成功了

> npm install -g fis3-smarty

可是

> fis3 server start --type php --rewrite

提示

> [INFO] Currently running fis3 ……
> checking java support : java not support

请问我非要安装java的环境不可吗？

**Comment by oxUnd** [comment]
@liguanrui 用来跑 web 服务，需要 java 环境。虽然 web 服务是可以替换的，但还是建议不要替换，这样才能有比较好的体验。

**Comment by liguanrui** [comment]
@xiangshouding 可是我有php的环境还不行？非要php和Java都有才可以吗？

**Comment by liguanrui** [comment]
?
