### ISSUE TITLE
fis-conf.js说明与演示文档不一致

### ISSUE THREAD

**Issue by kxbrand** [fex-team/fis3-smarty#6]
fis-conf.js说明与演示文档不一致

说明文档上是：
![fex-teamfis3-smarty](https://cloud.githubusercontent.com/assets/6490138/11265527/d5cb4418-8ed7-11e5-9c9c-4e83e37714dd.png)

```
// vi fis-conf.js

fis.require('smarty')(fis);
fis.set('namespace', <namespace>);

// default media is `dev`，
fis.media('dev').match('*', {
    useHash: false,
    optimizer: null
});
```

演示文档是则是：
![fis3-smartyfis-conf js at master fex-teamfis3-smarty](https://cloud.githubusercontent.com/assets/6490138/11265538/e272312c-8ed7-11e5-8f91-815942349e82.png)

```
require('fis3-smarty')(fis);
fis.set('namespace', 'common');
```

我的系统是wiin7 64位，按照说明文档上写的是可以执行的(`fis.require('smarty')(fis);`)，但是按照演示文档上写的是报错的。

**Comment by oxUnd** [comment]
好的

理论上 NODE_PATH 设置正确两种方法都 OK。

**Comment by kxbrand** [comment]
NODE_PATH设置的应该没有问题`C:\Users\Administrator\AppData\Roaming\npm\node_modules\`
