### ISSUE TITLE
fis3 server install server-env提示没有这个命令？

### ISSUE THREAD

**Issue by hinikai** [fex-team/fis3-smarty#7]
提示没有install的命令，默认只有star、stop、restart、info、open、clean的命令
fis3版本v3.3.0

**Comment by zhangtao07** [comment]
请提供错误详情，本地测试3.3.0没有问题。

**Comment by 2betop** [comment]
https://github.com/fex-team/fis3-smarty#本地测试服务

**Comment by zhangtao07** [comment]
fis3 >= 3.2.6 时 npm install -g fis3-server-smarty
低版本才是fis3 server install server-env
