### ISSUE TITLE
fis3-hook-commonjs  依赖更新

### ISSUE THREAD

**Issue by yueyao** [fex-team/fis3-smarty#8]
[增加 paths 从 component 中同步过来的功能](https://github.com/fex-team/fis3-hook-commonjs/commit/dc03e57b32b77c0dde912e029f988615e0760f95#diff-168726dbe96b3ce427e7fedce31bb0bcR30) 引起的bug `paths is not defined`
[https://github.com/fex-team/fis3-smarty/blob/master/package.json#L26](https://github.com/fex-team/fis3-smarty/blob/master/package.json#L26)

**Comment by 2betop** [comment]
哦，目前是用到啥组件了，我去更新到最新版本
